allowBuilds:
  esbuild: false
  sharp: false
  unrs-resolver: false
  playwright-final-summary-reporter: true
  "playwright-final-summary-reporter@https://codeload.github.com/sherifopel/playwright-final-summary-reporter/tar.gz/e3cb2eddc3ceba99ce5f750543a23bafa1178fc6": true
